=== SWRT-dev/asuswrt-bcm/release/src/router/samba-3.0.33/docs-xml/xslt/db2latex-xsl/xsl/latex.mapping.dtd
<!ELEMENT latexbindings	(latexmapping+)>
<!ELEMENT latexmapping 	(mapping+)>
<!ELEMENT mapping (line*)>
<!ELEMENT line (#PCDATA)>

<!ATTLIST latexmapping 
role	CDATA	#REQUIRED
>
<!ATTLIST mapping 
key	CDATA	#REQUIRED
text	CDATA	#REQUIRED
>

=== SWRT-dev/asuswrt-bcm/release/src/router/samba3/docs-xml/xslt/db2latex-xsl/xsl/latex.mapping.xml
<?xml version='1.0'?>
<!DOCTYPE latexbindings SYSTEM "latex.mapping.dtd" []>

<latexbindings>

    <!-- 	
    ################################################################
    Keywords
    %id%
    %title%
    ################################################################ -->	


    <!-- LaTeX mapping, role, BEGIN -->
    <latexmapping role="begin">

	<mapping key="abstract" text="">
	    <line>&#10;</line>
	    <line>% --------------------------------------------&#10;</line>
	    <line>% Abstract &#10;</line>
	    <line>% --------------------------------------------&#10;</line>
	    <line>\begin{abstract}&#10;</line>
	</mapping>	

	<mapping key="abstract-title" text="">
	    <line>&#10;</line>
	    <line>% --------------------------------------------&#10;</line>
	    <line>% Abstract &#10;</line>
	    <line>% --------------------------------------------&#10;</line>
      <line>\makeatletter\let\save@@abstractname\abstractname\makeatother&#10;</line>
      <line>\renewcommand{\abstractname}{%title%}&#10;</line>
	    <line>\begin{abstract}&#10;</line>
	</mapping>	

	<mapping key="admonition"	text="">
	    <line>&#10;</line>
	    <line>\begin{admonition}%title%% NOTICE: see the db2latex FAQ w.r.t db2latex variable $latex.admonition.path&#10;</line>
	</mapping>

	<mapping key="appendices-chapter"	text="">
	    <line>% ------------------------------------------------------------- &#10;</line>
	    <line>% Appendices start here&#10;</line>
	    <line>% -------------------------------------------------------------&#10;</line>
	    <line>\appendix&#10;</line>
	</mapping>

	<mapping key="appendices-section"	text=""/>

	<mapping key="appendix"		text="">
	    <line>&#10;</line>
	    <line>% -------------------------------------------------------------&#10;</line>
	    <line>% appendix:  %title% &#10;</line>
	    <line>% ------------------------------------------------------------- 	&#10;</line>
	    <line>\dbappendix{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="article"	text="">
    <line>\begin{document}&#10;</line>
	</mapping>

	<mapping key="bibliography-chapter" text="">
		<line>% ------------------------------------------- &#10;</line>
		<line>%&#10;</line>
		<line>%  Bibliography - chapter&#10;</line>
		<line>%&#10;</line>
		<line>% ------------------------------------------- &#10;</line>
	</mapping>

	<mapping key="bibliography-section" text=""/>

	<mapping key="blockquote"	text="">
		<line>\begin{quote}&#10;</line>
	</mapping>

	<mapping key="chapter"	text="">
	    <line>&#10;</line>
	    <line>% -------------------------------------------------------------&#10;</line>
	    <line>% Chapter %title% &#10;</line>
	    <line>% ------------------------------------------------------------- 	&#10;</line>
	    <line>\chapter{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="colophon" text="">
		<line>% -------------------------------------------------------------&#10;</line>
		<line>% Colophon &#10;</line>
		<line>% -------------------------------------------------------------&#10;</line>
		<line>\chapter*{%title%}%&#10;</line>
		<line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="dedication" text="">
		<line>% -------------------------------------------------------------&#10;</line>
		<line>% Dedication &#10;</line>
		<line>% -------------------------------------------------------------&#10;</line>
		<line>\chapter*{%title%}%&#10;</line>
		<line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="epigraph"	text="">
		<line>\begin{quote}&#10;</line>
	</mapping>

	<mapping key="figure"	text="">
	    <line>&#10;</line>
	    <line>% figure ------------------------------------------------------&#10;</line>
	    <line>\begin{figure}[%title%]&#10;</line>
	    <line>\begin{center}%&#10;</line>
	    <line>\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="index" text="">
		<line>\indexspace&#10;</line>
	</mapping>

	<mapping key="informalfigure"	text="">
	    <line>&#10;</line>
	    <line>% informalfigure ------------------------------------------------------&#10;</line>
	    <line>\begin{center}%&#10;</line>
	    <line>\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="keywordset"	text="">
	    <line>&#10;</line>
	    <line>% keywords ------------------------------------------------------&#10;</line>
	    <line><![CDATA[
\vspace{-.3em}{
\if@twocolumn\small\textit{%title%}\bfseries---$\!$%
\else\begin{center}\small\bfseries{%title%}\end{center}\begin{quote}\small%
\fi
]]></line>
	</mapping>

	<mapping key="table"	text="">
	    <line>&#10;</line>
	    <line>% table ------------------------------------------------------&#10;</line>
	    <line>\begin{table}[%title%]&#10;</line>
	    <line>\begin{center}%&#10;</line>
	    <line>\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="informaltable"	text="">
	    <line>&#10;</line>
	    <line>% tabular ------------------------------------------------------&#10;</line>
	    <line>\begin{center}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="equation"	text="">
	    <line>&#10;\begin{dbequation}&#10;</line>
	    <line>\begin{center}&#10;</line>
	    <line>\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="glossary"	text="">
	    <line>% ------------------------------------------------------------- &#10;</line>
	    <line>% &#10;</line>
	    <line>% GLOSSARY %title%&#10;</line>
	    <line>% &#10;</line>
	    <line>% ------------------------------------------------------------- &#10;</line>
	    <line>\dbglossary{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="glossdiv"	text="">
	    <line>% &#10;</line>
	    <line>% ------------------------------------------------------------- &#10;</line>
	    <line>\dbglossdiv{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	    <line>\noindent%&#10;</line>
	    <line>\begin{description}%&#10;</line>
	</mapping>

	<mapping key="glosslist"	text="">
	    <line>% &#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	    <line>\noindent%&#10;</line>
	    <line>\begin{description}%&#10;</line>
	</mapping>

	<mapping key="part"	text="">
	    <line>% ------------------------------------------------------------- &#10;</line>
	    <line>% &#10;</line>
	    <line>% PART %title%&#10;</line>
	    <line>% &#10;</line>
	    <line>% ------------------------------------------------------------- &#10;</line>
	    <line>\part{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="partintro"	text="">
	    <line>&#10;</line>
	    <line>% -------------------------------------------------------------&#10;</line>
	    <line>% PartIntro %title% &#10;</line>
	    <line>% ------------------------------------------------------------- 	&#10;</line>
	    <line>\chapter*{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="preface" text="">
		<line>% -------------------------------------------------------------&#10;</line>
		<line>% Preface &#10;</line>
		<line>% -------------------------------------------------------------&#10;</line>
		<line>\chapter*{%title%}%&#10;</line>
		<line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="refentry"	text="">
	    <line>% &#10;</line>
	    <line>% -------------------------------------------------------------&#10;</line>
	    <line>% Refentry &#10;</line>
	    <line>% ------------------------------------------------------------- 	&#10;</line>
	    <line>\section*{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="refsect1"		text="&#10;\subsection*{%title%}&#10;\label{%id%}&#10;"/>
	<mapping key="refsect2"		text="&#10;\subsubsection*{%title%}&#10;\label{%id%}&#10;"/>
	<mapping key="refsect3"		text="&#10;\paragraph*{%title%}&#10;\label{%id%}&#10;"/>

	<mapping key="reference" text="">
	    <line>% &#10;</line>
	    <line>% -------------------------------------------------------------&#10;</line>
	    <line>% Reference &#10;</line>
	    <line>% ------------------------------------------------------------- 	&#10;</line>
	    <line>\chapter{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="revhistory" text="">
	    <line>&#10;</line>
	    <line>% ------------------------   &#10;</line>
	    <line>% RevHistory                                 &#10;</line>
	    <line>% ------------------------   &#10;</line>
	    <line>\pagebreak&#10;</line>
	    <line>\section*{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	    <line>\begin{center}&#10;</line>
	    <line>\begin{tt}&#10;</line>
	    <line>\begin{tabular}{|l||l|l|} \hline&#10;</line>
	</mapping>

	<mapping key="example"		text="&#10;\begin{example}%&#10;\hypertarget{%id%}{}%&#10;"/>

	<mapping key="programlisting"	text="&#10;\begin{program}%&#10;"/>

	<mapping key="sect1"		text="">
	    <line>&#10;</line>
	    <line>% ------------------------   &#10;</line>
	    <line>% Section &#10;</line>
	    <line>\section{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="sect1*"		text="">
	    <line>&#10;</line>
	    <line>% ------------------------   &#10;</line>
	    <line>% Section &#10;</line>
	    <line>\section*{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="sect2"		text="">
	    <line>\subsection{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="sect2*"		text="">
	    <line>\subsection*{%title%}&#10;</line>
	    <line>\label{%id%}\hypertarget{%id%}{}%&#10;</line>
	</mapping>

	<mapping key="sect3"		text="">
